export const START_FETCHING_REPOS = 'features/Repos/START_FETCHING_REPOS';
export const ERROR_FETCHING_REPOS = 'features/Repos/ERROR_FETCHING_REPOS';
export const SUCCESS_FETCHING_REPOS = 'features/Repos/SUCCESS_FETCHING_REPOS';